config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :sessions => "sessions", :registrations => "registrations" }
  root 'users#index'

    resources :users
    resources :admins do
      collection do
        get "edit_permission/:id", action: 'edit_permission', as: :edit_permission
        post "active"
      end
    end
  resources :admin_permissions
  resources :theme_customizations do
    collection do
      get 'edit_theme'
    end
  end
  resources :user_informations do
    collection do
      post 'profile_picture_change'
      post 'cropped_profile_picture_save'
    end
  end

  resources :food_categories
  resources :food_sub_categories
  resources :items do
    collection do
      get "add_to_card/:id", action: 'add_to_card', as: :add_to_card
      get "remove_from_card/:id", action: 'remove_from_card', as: :remove_from_card
      get "quantity_decrease/:id", action: 'quantity_decrease', as: :quantity_decrease
      get "order_place"
    end
  end
  resources :sub_items
  resources :customer_orders
  resources :ordered_items
  resources :product_colors
  resources :product_types
  resources :parties do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :buyers do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :bank_accounts
  resources :bank_balance_entries do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :bank_balance_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :party_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :buyer_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :expense_categories
  resources :expenses do
    collection do
      get 'search_expenses_by_category'
    end
  end

  resources :main_costs do
    collection do
      get 'expense_load_according_to_expense_category'
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :cash_balance_entries do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :cash_balance_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_product_adds do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_product_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_reports
  resources :employees do
    collection do
      post 'active'
      post 'profile_picture_change'
      post 'cropped_profile_picture_save'
    end
  end
  resources :employee_leaves do
    collection do
      get 'leave_search_according_to_employee'
      get 'leave_search_according_to_employee_download'
    end
  end

  resources :employee_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :product_imports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :product_exports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :employee_salary_adds do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :total_expense_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :total_income_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :balance_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :company_informations

end

app/models/bank_balance_entry.rb
class BankBalanceEntry < ActiveRecord::Base


  # 0 for original bank balance entry
  # 1 for original buyer payment


  validates :amount, :bank_account_id, :from_where, :user_id, presence: true
  validates_numericality_of :amount, :greater_than_or_equal_to => 1

  belongs_to :bank_account
  belongs_to :user
end

app/controllers/bank_balance_entries_controller.rb
class BankBalanceEntriesController < ApplicationController

  def index

  end

  def new
    @bank_balance_entry = BankBalanceEntry.new
  end

  def create
    @bank_balance_entry = BankBalanceEntry.new(params_bank_balance_entry)
    if @bank_balance_entry.save
      flash[:notice] = 'Bank balance added successfully.'
      redirect_to new_bank_balance_entry_path
    else
      render 'new'
    end
  end

  def monthly_and_yearly_report
    @date = Date.today
    @month = Month.find(@date.strftime("%-m").to_i) rescue nil
    @year= Year.find_by_name(@date.strftime("%Y").to_s) rescue nil
    @reports = BankBalanceEntry.where(:created_at => Date.today.beginning_of_month..Date.today.end_of_month)

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def monthly_and_yearly_report_search
    @month = Month.find(params[:month_id].to_i) rescue nil
    @year= Year.find_by_name(params[:year_id].to_s) rescue nil
    @bank_account = BankAccount.find(params[:bank_account_id]) rescue nil

    if params[:month_id] !='' && params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i ,params[:month_id].to_i)
      @reports = BankBalanceEntry.where(:created_at => @year_month.beginning_of_month..@year_month.end_of_month)
    elsif params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i)
      @reports = BankBalanceEntry.where(:created_at => @year_month.beginning_of_year..@year_month.end_of_year)
    else
      @reports = BankBalanceEntry.all
    end

    if @bank_account
      @reports = @reports.where(:bank_account_id => @bank_account.id)
    end
  end

  def monthly_and_yearly_report_download
    @month = Month.find(params[:month_id].to_i) rescue nil
    @year= Year.find_by_name(params[:year_id].to_s) rescue nil
    @bank_account = BankAccount.find(params[:bank_account_id]) rescue nil

    if params[:month_id] !='' && params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i ,params[:month_id].to_i)
      @reports = BankBalanceEntry.where(:created_at => @year_month.beginning_of_month..@year_month.end_of_month)
    elsif params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i)
      @reports = BankBalanceEntry.where(:created_at => @year_month.beginning_of_year..@year_month.end_of_year)
    else
      @reports = BankBalanceEntry.all
    end

    if @bank_account
      @reports = @reports.where(:bank_account_id => @bank_account.id)
    end

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def date_to_date_report
    @date = Date.today
    @start_date = @date.beginning_of_month
    @end_date = @date.end_of_month
    @reports = BankBalanceEntry.where(:created_at => Date.today.beginning_of_month..Date.today.end_of_month)

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def date_to_date_report_search
    @bank_account = BankAccount.find(params[:bank_account_id]) rescue nil
    @start_date = Date.parse(params[:start_date])
    @end_date = Date.parse(params[:end_date])
    @reports = BankBalanceEntry.where(:created_at => @start_date.beginning_of_day..@end_date.end_of_day)
    if @bank_account
      @reports = @reports.where(:bank_account_id => @bank_account.id)
    end
  end

  def date_to_date_report_download
    @bank_account = BankAccount.find(params[:bank_account_id]) rescue nil
    @start_date = Date.parse(params[:start_date])
    @end_date = Date.parse(params[:end_date])
    @reports = BankBalanceEntry.where(:created_at => @start_date.beginning_of_day..@end_date.end_of_day)
    if @bank_account
      @reports = @reports.where(:bank_account_id => @bank_account.id)
    end

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end


  protected
  def params_bank_balance_entry
    params.require(:bank_balance_entry).permit(:from_where, :amount, :remarks).merge(:bank_account_id => params[:bank_account_id], :user_id => current_user.id)
  end

end

app/helpers/bank_balance_entries_helper.rb
module BankBalanceEntriesHelper
end

app/views/bank_balance_entries/_date_to_date_search_header_info.html.erb
<div class="row">
  <div class="col-md-6">
    <h4 class="">
      <span class="text-left">Bank balance entry reports</span>
    </h4>
    <h4>
      <span class="text-right">Bank Account: <%= @bank_account ? @bank_account.account_number : 'All'  %> </span>
    </h4>
    <h5>
      <% bank_account_id = '' %>
      <% bank_account_id = @bank_account.id if @bank_account %>
      <%= link_to date_to_date_report_download_bank_balance_entries_path(:format => :xls, :bank_account_id => bank_account_id, :start_date=> @start_date, :end_date=> @end_date), target: '_blank'  do %>
          <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
      <% end %>
      <%= link_to date_to_date_report_download_bank_balance_entries_path(:format => :pdf, :bank_account_id => bank_account_id, :start_date=> @start_date, :end_date=> @end_date), target: '_blank'  do %>
          <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
      <% end %>
    </h5>
  </div>
  <div class="col-md-6 text-right">
    <h4>
      <span class="text-right">Start date:  <%= @start_date.strftime("%d-%b, %Y") if @start_date %> </span>
    </h4>
    <h4>
      <span class="text-right">End date:  <%= @end_date.strftime("%d-%b, %Y") if @end_date %> </span>
    </h4>
  </div>
</div>

app/views/bank_balance_entries/_form.html.erb
<div class="row border-bottom white-bg dashboard-header">
  <!-- begin col-6 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse" data-sortable-id="form-stuff-3">

      <div class="panel-body">
        <%= form_for @bank_balance_entry do |f| %>
            <fieldset>
              <div class="form-group">
                <% if @bank_balance_entry.errors.any? %>
                    <div id="error_explanation">
                      <h2>
                        <%= pluralize(@bank_balance_entry.errors.count, "Error") %>
                      </h2>
                      <ul>
                        <% @bank_balance_entry.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>
              </div>

              <div class="form-group">
                <label for="exampleInputEmail1">Select bank account*</label>
                <%= select_tag 'bank_account_id', options_from_collection_for_select(BankAccount.where(:isActive => true),:id, :bank_name, :selected=>@bank_balance_entry.bank_account_id), {:prompt=>'Select bank account', :class => 'form-control' } %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Amount*</label>
                <%= f.text_field :amount, autofocus: true, :class=>"form-control", :placeholder=>"Balance*" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">From where*</label>
                <%= f.text_field :from_where, autofocus: true, :class=>"form-control", :placeholder=>"From where*" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Remarks</label>
                <%= f.text_area :remarks, autofocus: true, :class=>"form-control", :placeholder=>"Remarks" %>
              </div>


              <%= f.submit "Submit", :class=>'btn btn-sm btn-primary m-r-5', data: { disable_with: "Submiting...", confirm: "Are you sure? you want to add balance." } %>
              <%= link_to 'Back', :back ,data: { no_turbolink: true }, :class => 'btn btn-sm btn-default' %>
            </fieldset>
        <% end %>
      </div>
    </div>
    <!-- end panel -->
  </div>
</div>


<script>
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
    });
</script>

app/views/bank_balance_entries/_reports_header_info.html.erb
<div class="row">
  <div class="col-md-6">
    <h4 class="">
      <span class="text-left">Bank balance entry reports</span>
    </h4>
    <h4>
      <span class="text-right">Bank Account: <%= @bank_account ? @bank_account.account_number : 'All'  %> </span>
    </h4>
    <h5>
      <% bank_account_id = '' %>
      <% year_id = '' %>
      <% month_id = '' %>
      <% month_id = @month.id if @month %>
      <% year_id = @year.name if @year %>
      <% bank_account_id = @bank_account.id if @bank_account %>
      <%= link_to monthly_and_yearly_report_download_bank_balance_entries_path(:format => :xls, :bank_account_id => bank_account_id, :year_id=> year_id, :month_id=> month_id), target: '_blank'  do %>
          <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
      <% end %>
      <%= link_to monthly_and_yearly_report_download_bank_balance_entries_path(:format => :pdf, :bank_account_id => bank_account_id, :year_id=> year_id, :month_id=> month_id), target: '_blank'  do %>
          <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
      <% end %>
    </h5>
  </div>
  <div class="col-md-6 text-right">
    <h4>
      <span class="text-right">Month: <%= @month ? @month.name : 'All'  %> </span>
    </h4>
    <h4>
      <span class="text-right">Year: <%= @year ? @year.name : 'All'  %> </span>
    </h4>
  </div>
</div>

app/views/bank_balance_entries/_reports_list_view_partial.pdf.erb
<div class="panel-body">
  <div class="table-responsive">
    <% if @reports.any? %>
        <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
          <thead>
          <tr>
            <th>Date</th>
            <th>Bank name</th>
            <th>Account No</th>
            <th class="text-center">From where</th>
            <th class="text-center">Amount(tk)</th>
            <th class="text-center">remarks</th>
            <th class="text-center">Added by</th>
          </tr>
          </thead>
          <tbody>

          <% @reports.each do |report| %>
              <tr>
                <td>
                  <%= report.created_at.strftime("%d-%m-%Y") %>
                </td>
                <td>
                  <%= link_to report.bank_account.bank_name, bank_account_path(report.bank_account), data: { no_turbolink: true } %>
                </td>
                <td>
                  <%= link_to report.bank_account.account_number, bank_account_path(report.bank_account), data: { no_turbolink: true } %>
                </td>
                <td class="text-center">
                  <%= report.from_where %>
                </td>
                <td class="text-right">
                  <%= report.amount %>
                </td>
                <td style="max-width: 150px; font-size: 7px; color: #000000" class="text-center">
                  <%= report.remarks %>
                </td>
                <td>
                  <%= link_to report.user.email, user_information_path(report.user.user_information), data: { no_turbolink: true } %>
                </td>

              </tr>
          <% end %>
          <tr>
            <td style="background:#E5E5E5" colspan="4"  class="text-center">Total amount</td>
            <td style="background:#E5E5E5;" class="text-right">
              <%= @reports.sum(:amount) %>
            </td>
            <td colspan="2"></td>
          </tr>


          </tbody>
        </table>
    <% else %>
        <h4>There is no balance entry report in this duration.</h4>
    <% end %>

  </div>
</div>

app/views/bank_balance_entries/_reports_list_view_partial.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>


      <Row>
        <th>Date</th>
        <Cell><Data ss:Type="String">Serial No</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Bank name</Data></Cell>
        <Cell><Data ss:Type="String">Account No</Data></Cell>
        <Cell><Data ss:Type="String">From where</Data></Cell>
        <Cell><Data ss:Type="String">Amount(tk)</Data></Cell>
        <Cell><Data ss:Type="String">Remarks</Data></Cell>
        <Cell><Data ss:Type="String">Added by</Data></Cell>
      </Row>
      <% if @reports %>
          <% if @reports.any? %>
              <% std_count = 1 %>

              <% @reports.each do |report| %>
                  <Row>
                    <Cell><Data ss:Type="Number"><%= std_count %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.created_at.strftime('%d-%m-%Y') %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.bank_account.bank_name %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.bank_account.account_number %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.from_where %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= report.amount %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.remarks %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.user.email  %></Data></Cell>
                  </Row>
                  <% std_count = std_count + 1 %>
              <% end %>
              <Row>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell><Data ss:Type="String">Total amount</Data></Cell>
                <Cell><Data ss:Type="Number"><%= @reports.sum(:amount) %></Data></Cell>
                <Cell></Cell>
              </Row>

              <Row></Row>
              <Row></Row>
              <Row></Row>
              <Row></Row>
              <Row></Row>

              <Row>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell><Data ss:Type="String">Total amount</Data></Cell>
                <Cell><Data ss:Type="Number"><%= @reports.sum(:amount) if @reports.any? %></Data></Cell>
                <Cell></Cell>
              </Row>


    <% else %>
              <Row>
                <Cell><Data ss:Type="String">There is no balance entry report in this duration.</Data></Cell>
              </Row>
          <% end %>
      <% end %>

    </Table>
  </Worksheet>
</Workbook>

app/views/bank_balance_entries/date_to_date_report.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-md-3">
    <h3>Date to Date Reports</h3>

  </div>
  <div class="col-md-9">
    <h2 class="text-right">
      <%= select_tag 'bank_account_id', options_from_collection_for_select(BankAccount.all,:id, :account_number), { :class =>'btn btn-white',:include_blank => 'Select bank account' } %>
      <input type="text" placeholder="Start date" class="datepicker btn btn-white start_date" value="<%= @start_date %>"> to
      <input type="text" placeholder="Start date" class="datepicker btn btn-white end_date" value="<%= @end_date %>">
      <span id="report_search" class="btn btn-default">
          <i class="fa fa-search"></i>
          Search
        </span>
    </h2>
  </div>
</div>


<!-- begin page #content -->

<!-- begin row -->
<div class="row border-bottom white-bg dashboard-header">

  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <div class="panel-heading" id="reports_header_info">
        <div class="row">
          <div class="col-md-6">
            <h4 class="">
              <span class="text-left">Bank balance entry reports</span>
            </h4>
            <h4>
              <span class="text-right">Bank Account: <%= @bank_account ? @bank_account.account_number : 'All'  %> </span>
            </h4>
            <h5>
              <%= link_to date_to_date_report_bank_balance_entries_path(:format => :xls), target: '_blank'  do %>
                  <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
              <% end %>
              <%= link_to date_to_date_report_bank_balance_entries_path(:format => :pdf), target: '_blank'  do %>
                  <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
              <% end %>
            </h5>
          </div>
          <div class="col-md-6 text-right">
            <h4>
              <span class="text-right">Start date:  <%= @start_date.strftime("%d-%b, %Y") if @start_date %> </span>
            </h4>
            <h4>
              <span class="text-right">End date:  <%= @end_date.strftime("%d-%b, %Y") if @end_date %> </span>
            </h4>
          </div>
        </div>
      </div>
      <div id="reports_holder">
        <%= render 'bank_balance_entries/reports_list_view_partial' %>
      </div>
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>
<!-- end row -->

<!-- end page #content -->



<script>

    $('.datepicker').datepicker({
        autoclose: true,
        todayBtn: "linked",
        format: 'yyyy/mm/dd'
    });

    $('#report_search').click(function(){
        var bank_account_id =$('#bank_account_id').val();
        var start_date =$('.start_date').val();
        var end_date =$('.end_date').val();
        var spinner = $('<div style="text-align: center"><img src="/img/loading_spinner.gif"></div>');
        $('#reports_holder').html(spinner)
        $.ajax({
            url:'<%= date_to_date_report_search_bank_balance_entries_path %>',
            type: 'get',
            data:{ bank_account_id: bank_account_id, start_date: start_date, end_date: end_date }
        });
    });

</script>

app/views/bank_balance_entries/date_to_date_report.xls.erb
<%= render 'bank_balance_entries/reports_list_view_partial' %>

app/views/bank_balance_entries/monthly_and_yearly_report.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-md-4">
    <h2>Bank Balance Entry Reports</h2>

  </div>
  <div class="col-md-8">
    <h2 class="text-right">
        <%= select_tag 'bank_account_id', options_from_collection_for_select(BankAccount.all,:id, :account_number), { :class =>'btn btn-white',:include_blank => 'Select bank account' } %>
        <%= select_tag 'month_id', options_from_collection_for_select(Month.all,:id, :name, :selected => @month.id), { :class =>'btn btn-white',:include_blank => 'Select month' } %>
        <%= select_tag 'year_id', options_from_collection_for_select(Year.all,:name, :name, :selected => @year.name), { :class =>'btn btn-white',:include_blank => 'Select year' } %>
        <span id="report_search" class="btn btn-default">
          <i class="fa fa-search"></i>
          Search
        </span>
    </h2>
  </div>
</div>


<!-- begin page #content -->

<!-- begin row -->
<div class="row border-bottom white-bg dashboard-header">

  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <div class="panel-heading" id="reports_header_info">
        <div class="row">
          <div class="col-md-6">
            <h4 class="">
              <span class="text-left">Bank balance entry reports</span>
            </h4>
            <h4>
              <span class="text-right">Bank Account: <%= @bank_account ? @bank_account.account_number : 'All'  %> </span>
            </h4>
            <h5>
              <%= link_to monthly_and_yearly_report_bank_balance_entries_path(:format => :xls), target: '_blank'  do %>
                  <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
              <% end %>
              <%= link_to monthly_and_yearly_report_bank_balance_entries_path(:format => :pdf), target: '_blank'  do %>
                  <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
              <% end %>
            </h5>
          </div>
          <div class="col-md-6 text-right">
            <h4>
              <span class="text-right">Month: <%= @month ? @month.name : 'All'  %> </span>
            </h4>
            <h4>
              <span class="text-right">Year: <%= @year ? @year.name : 'All'  %> </span>
            </h4>
          </div>
        </div>
      </div>
     <div id="reports_holder">
       <%= render 'bank_balance_entries/reports_list_view_partial' %>
     </div>
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>
<!-- end row -->

<!-- end page #content -->



<script>

  $('#report_search').click(function(){
      var bank_account_id =$('#bank_account_id').val();
      var year_id =$('#year_id').val();
      var month_id =$('#month_id').val();
      var spinner = $('<div style="text-align: center"><img src="/img/loading_spinner.gif"></div>');
      $('#reports_holder').html(spinner)
      $.ajax({
          url:'<%= monthly_and_yearly_report_search_bank_balance_entries_path %>',
          type: 'get',
          data:{ bank_account_id: bank_account_id, year_id: year_id, month_id:month_id }
      });
  });

</script>