config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :sessions => "sessions", :registrations => "registrations" }
  root 'users#index'

    resources :users
    resources :admins do
      collection do
        get "edit_permission/:id", action: 'edit_permission', as: :edit_permission
        post "active"
      end
    end
  resources :admin_permissions
  resources :theme_customizations do
    collection do
      get 'edit_theme'
    end
  end
  resources :user_informations do
    collection do
      post 'profile_picture_change'
      post 'cropped_profile_picture_save'
    end
  end

  resources :food_categories
  resources :food_sub_categories
  resources :items do
    collection do
      get "add_to_card/:id", action: 'add_to_card', as: :add_to_card
      get "remove_from_card/:id", action: 'remove_from_card', as: :remove_from_card
      get "quantity_decrease/:id", action: 'quantity_decrease', as: :quantity_decrease
      get "order_place"
    end
  end
  resources :sub_items
  resources :customer_orders
  resources :ordered_items
  resources :product_colors
  resources :product_types
  resources :parties do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :buyers do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :bank_accounts
  resources :bank_balance_entries do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :bank_balance_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :party_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :buyer_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :expense_categories
  resources :expenses do
    collection do
      get 'search_expenses_by_category'
    end
  end

  resources :main_costs do
    collection do
      get 'expense_load_according_to_expense_category'
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :cash_balance_entries do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :cash_balance_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_product_adds do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_product_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_reports
  resources :employees do
    collection do
      post 'active'
      post 'profile_picture_change'
      post 'cropped_profile_picture_save'
    end
  end
  resources :employee_leaves do
    collection do
      get 'leave_search_according_to_employee'
      get 'leave_search_according_to_employee_download'
    end
  end

  resources :employee_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :product_imports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :product_exports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :employee_salary_adds do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :total_expense_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :total_income_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :balance_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :company_informations

end

app/controllers/total_expense_reports_controller.rb
class TotalExpenseReportsController < ApplicationController


  def monthly_and_yearly_report
    @date = Date.today
    @month = Month.find(@date.strftime("%-m").to_i) rescue nil
    @year= Year.find_by_name(@date.strftime("%Y").to_s) rescue nil
    @cash_reports = CashBalanceOut.where(:created_at => Date.today.beginning_of_month..Date.today.end_of_month)
    @bank_reports = BankBalanceOut.where(:created_at => Date.today.beginning_of_month..Date.today.end_of_month)
    @reports = @cash_reports + @bank_reports
    @reports = @reports.sort_by(&:created_at)

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def monthly_and_yearly_report_search
    @month = Month.find(params[:month_id].to_i) rescue nil
    @year= Year.find_by_name(params[:year_id].to_s) rescue nil

    if params[:month_id] !='' && params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i ,params[:month_id].to_i)
      @cash_reports = CashBalanceOut.where(:created_at => @year_month.beginning_of_month..@year_month.end_of_month)
      @bank_reports = BankBalanceOut.where(:created_at => @year_month.beginning_of_month..@year_month.end_of_month)
    elsif params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i)
      @cash_reports = CashBalanceOut.where(:created_at => @year_month.beginning_of_year..@year_month.end_of_year)
      @bank_reports = BankBalanceOut.where(:created_at => @year_month.beginning_of_year..@year_month.end_of_year)
    else
      @cash_reports = CashBalanceOut.all
      @bank_reports = BankBalanceOut.all
    end

    @reports = @cash_reports + @bank_reports
    @reports = @reports.sort_by(&:created_at)

  end

  def monthly_and_yearly_report_download
    @month = Month.find(params[:month_id].to_i) rescue nil
    @year= Year.find_by_name(params[:year_id].to_s) rescue nil

    if params[:month_id] !='' && params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i ,params[:month_id].to_i)
      @cash_reports = CashBalanceOut.where(:created_at => @year_month.beginning_of_month..@year_month.end_of_month)
      @bank_reports = BankBalanceOut.where(:created_at => @year_month.beginning_of_month..@year_month.end_of_month)
    elsif params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i)
      @cash_reports = CashBalanceOut.where(:created_at => @year_month.beginning_of_year..@year_month.end_of_year)
      @bank_reports = BankBalanceOut.where(:created_at => @year_month.beginning_of_year..@year_month.end_of_year)
    else
      @cash_reports = CashBalanceOut.all
      @bank_reports = BankBalanceOut.all
    end

    @reports = @cash_reports + @bank_reports
    @reports = @reports.sort_by(&:created_at)

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def date_to_date_report
    @date = Date.today
    @start_date = @date.beginning_of_month
    @end_date = @date.end_of_month
    @cash_reports = CashBalanceOut.where(:created_at => Date.today.beginning_of_month..Date.today.end_of_month)
    @bank_reports = BankBalanceOut.where(:created_at => Date.today.beginning_of_month..Date.today.end_of_month)

    @reports = @cash_reports + @bank_reports
    @reports = @reports.sort_by(&:created_at)

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def date_to_date_report_search
    @start_date = Date.parse(params[:start_date])
    @end_date = Date.parse(params[:end_date])
    @cash_reports = CashBalanceOut.where(:created_at => @start_date.beginning_of_day..@end_date.end_of_day)
    @bank_reports = BankBalanceOut.where(:created_at => @start_date.beginning_of_day..@end_date.end_of_day)

    @reports = @cash_reports + @bank_reports
    @reports = @reports.sort_by(&:created_at)

  end

  def date_to_date_report_download
    @start_date = Date.parse(params[:start_date])
    @end_date = Date.parse(params[:end_date])
    @cash_reports = CashBalanceOut.where(:created_at => @start_date.beginning_of_day..@end_date.end_of_day)
    @bank_reports = BankBalanceOut.where(:created_at => @start_date.beginning_of_day..@end_date.end_of_day)

    @reports = @cash_reports + @bank_reports
    @reports = @reports.sort_by(&:created_at)

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end


end

app/helpers/total_expense_reports_helper.rb
module TotalExpenseReportsHelper
end

app/views/total_expense_reports/_date_to_date_search_header_info.html.erb
<div class="row">
  <div class="col-md-6">
    <h4 class="">
      <span class="text-left">Total expense reports</span>
    </h4>
    <h5>
      <%= link_to date_to_date_report_download_total_expense_reports_path(:format => :xls, :start_date=> @start_date, :end_date=> @end_date), target: '_blank'  do %>
          <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
      <% end %>
      <%= link_to date_to_date_report_download_total_expense_reports_path(:format => :pdf, :start_date=> @start_date, :end_date=> @end_date), target: '_blank'  do %>
          <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
      <% end %>
    </h5>
  </div>
  <div class="col-md-6 text-right">
    <h4>
      <span class="text-right">Start date:  <%= @start_date.strftime("%d-%b, %Y") if @start_date %> </span>
    </h4>
    <h4>
      <span class="text-right">End date:  <%= @end_date.strftime("%d-%b, %Y") if @end_date %> </span>
    </h4>
  </div>
</div>

app/views/total_expense_reports/_reports_list_view_partial.html.erb
<div class="panel-body">
  <div class="table-responsive">
    <% if @reports.any? %>
        <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
          <thead>
          <tr>
            <th>Date</th>
            <th class="text-center">Type</th>
            <th class="text-center">Bank/Cash</th>
            <th class="text-center">To whom</th>
            <th class="text-center">Amount(tk)</th>
            <th class="text-center">remarks</th>
          </tr>
          </thead>
          <tbody>
          <% total_expense_amount = 0 %>
          <% @reports.each do |report| %>
              <% total_expense_amount += report.amount %>
              <tr>
                <td>
                  <%= report.created_at.strftime("%d-%m-%Y") %>
                </td>
                <td class="text-center">
                  <%= expense_type_return(report.flag) %>
                </td>
                <td class="text-center">
                  <% if report.model_name.name == 'BankBalanceOut'  %>
                  bank: <%= report.bank_account.account_number %>
                  <% elsif report.model_name.name == 'CashBalanceOut'  %>
                  cash
                  <% end %>
                </td>
                <td class="text-center">
                  <%= report.to_whom %>
                </td>
                <td class="text-right">
                  <%= report.amount %>
                </td>
                <td style="max-width: 150px; font-size: 8px; color: #000000" class="text-center">
                  <%= report.remarks %>
                </td>

              </tr>
          <% end %>
          <tr>
            <td style="background:#E5E5E5" colspan="4"  class="text-center">Total amount</td>
            <td style="background:#E5E5E5;" class="text-right">
              <%= total_expense_amount %>
            </td>
            <td colspan=""></td>
          </tr>


          </tbody>
        </table>
    <% else %>
        <h4>There is no expense report in this duration.</h4>
    <% end %>

  </div>
</div>

app/views/total_expense_reports/_reports_list_view_partial.pdf.erb
<div class="panel-body">
  <div class="table-responsive">
    <% if @reports.any? %>
        <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
          <thead>
          <tr>
            <th>Date</th>
            <th class="text-center">Type</th>
            <th class="text-center">Bank/Cash</th>
            <th class="text-center">To whom</th>
            <th class="text-center">Amount(tk)</th>
            <th class="text-center">remarks</th>
          </tr>
          </thead>
          <tbody>
          <% total_expense_amount = 0 %>
          <% @reports.each do |report| %>
              <% total_expense_amount += report.amount %>
              <tr>
                <td>
                  <%= report.created_at.strftime("%d-%m-%Y") %>
                </td>
                <td class="text-center">
                  <%= expense_type_return(report.flag) %>
                </td>
                <td class="text-center">
                  <% if report.model_name.name == 'BankBalanceOut'  %>
                      bank: <%= report.bank_account.account_number %>
                  <% elsif report.model_name.name == 'CashBalanceOut'  %>
                      cash
                  <% end %>
                </td>
                <td class="text-center">
                  <%= report.to_whom %>
                </td>
                <td class="text-right">
                  <%= report.amount %>
                </td>
                <td style="max-width: 150px; font-size: 8px; color: #000000" class="text-center">
                  <%= report.remarks %>
                </td>

              </tr>
          <% end %>
          <tr>
            <td style="background:#E5E5E5" colspan="4"  class="text-center">Total amount</td>
            <td style="background:#E5E5E5;" class="text-right">
              <%= total_expense_amount %>
            </td>
            <td colspan=""></td>
          </tr>


          </tbody>
        </table>
    <% else %>
        <h4>There is no expense report in this duration.</h4>
    <% end %>

  </div>
</div>

app/views/total_expense_reports/_reports_list_view_partial.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>


      <Row>
        <th>Date</th>
        <Cell><Data ss:Type="String">Serial No</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Type</Data></Cell>
        <Cell><Data ss:Type="String">Bank/Cash</Data></Cell>
        <Cell><Data ss:Type="String">To whom</Data></Cell>
        <Cell><Data ss:Type="String">Amount(tk)</Data></Cell>
        <Cell><Data ss:Type="String">Remarks</Data></Cell>
      </Row>
      <% if @reports %>
          <% if @reports.any? %>
              <% std_count = 1 %>
              <% total_expense_amount = 0 %>
              <% @reports.each do |report| %>
                  <% total_expense_amount += report.amount %>
                  <Row>
                    <Cell><Data ss:Type="Number"><%= std_count %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.created_at.strftime('%d-%m-%Y') %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= expense_type_return(report.flag) %></Data></Cell>
                    <Cell>
                      <Data ss:Type="String">
                        <% if report.model_name.name == 'BankBalanceOut'  %>
                            bank: <%= report.bank_account.account_number %>
                        <% elsif report.model_name.name == 'CashBalanceOut'  %>
                            cash
                        <% end %>
                      </Data>
                    </Cell>
                    <Cell><Data ss:Type="String"><%= report.to_whom %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= report.amount %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.remarks %></Data></Cell>
                  </Row>
                  <% std_count = std_count + 1 %>
              <% end %>
              <Row>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell><Data ss:Type="String">Total amount</Data></Cell>
                <Cell><Data ss:Type="Number"><%= total_expense_amount %></Data></Cell>
                <Cell></Cell>
              </Row>

              <Row></Row>
              <Row></Row>
              <Row></Row>
              <Row></Row>
              <Row></Row>

              <Row>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell><Data ss:Type="String">Total amount</Data></Cell>
                <Cell><Data ss:Type="Number"><%= total_expense_amount if @reports.any? %></Data></Cell>
                <Cell></Cell>
              </Row>


    <% else %>
              <Row>
                <Cell><Data ss:Type="String">There is no expense report in this duration.</Data></Cell>
              </Row>
          <% end %>
      <% end %>

    </Table>
  </Worksheet>
</Workbook>

app/views/total_expense_reports/date_to_date_report.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-md-3">
    <h3>Date to Date Reports</h3>

  </div>
  <div class="col-md-9">
    <h2 class="text-right">
      <input type="text" placeholder="Start date" class="datepicker btn btn-white start_date" value="<%= @start_date %>"> to
      <input type="text" placeholder="Start date" class="datepicker btn btn-white end_date" value="<%= @end_date %>">
      <span id="report_search" class="btn btn-default">
          <i class="fa fa-search"></i>
          Search
        </span>
    </h2>
  </div>
</div>


<!-- begin page #content -->

<!-- begin row -->
<div class="row border-bottom white-bg dashboard-header">

  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <div class="panel-heading" id="reports_header_info">
        <div class="row">
          <div class="col-md-6">
            <h4 class="">
              <span class="text-left">Total expense reports</span>
            </h4>

            <h5>
              <%= link_to date_to_date_report_total_expense_reports_path(:format => :xls), target: '_blank'  do %>
                  <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
              <% end %>
              <%= link_to date_to_date_report_total_expense_reports_path(:format => :pdf), target: '_blank'  do %>
                  <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
              <% end %>
            </h5>
          </div>
          <div class="col-md-6 text-right">
            <h4>
              <span class="text-right">Start date:  <%= @start_date.strftime("%d-%b, %Y") if @start_date %> </span>
            </h4>
            <h4>
              <span class="text-right">End date:  <%= @end_date.strftime("%d-%b, %Y") if @end_date %> </span>
            </h4>
          </div>
        </div>
      </div>
      <div id="reports_holder">
        <%= render 'total_expense_reports/reports_list_view_partial' %>
      </div>
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>
<!-- end row -->

<!-- end page #content -->



<script>

    $('.datepicker').datepicker({
        autoclose: true,
        todayBtn: "linked",
        format: 'yyyy/mm/dd'
    });

    $('#report_search').click(function(){

        var start_date =$('.start_date').val();
        var end_date =$('.end_date').val();
        var spinner = $('<div style="text-align: center"><img src="/img/loading_spinner.gif"></div>');
        $('#reports_holder').html(spinner)
        $.ajax({
            url:'<%= date_to_date_report_search_total_expense_reports_path %>',
            type: 'get',
            data:{ start_date: start_date, end_date: end_date }
        });
    });

</script>

app/views/total_expense_reports/date_to_date_report.pdf.erb
<style>
    table {
        font-size: 10px;
        height:auto;
        margin-top:20px;
        border-collapse: collapse;
    }
    table tr td {
        padding:5px 0 5px 5px;
        text-align: center;
        font-weight: 300;
        font-family: Arial, Helvetica, sans-serif;
        color: #353535;
        -webkit-font-smoothing: antialiased;
        font-size: 10px;
        border: .01em solid #dddddd;


    }
    table tr td a {
        text-decoration: none;
        color: #000000;
    }
    table thead tr td {
        padding:5px 0 5px 5px;
        text-align: center;
        font-weight: 400;
        font-family: Arial, Helvetica, sans-serif;
        color: #353535;
        -webkit-font-smoothing: antialiased;
        font-size: 10px;
        border: .01em solid #dadada;
    }
    h4 {
        display: block;
        margin-top: 0.5em;
        margin-bottom: 0.5em;
        margin-left: 0;
        margin-right: 0;
        font-weight: normal;
        font-size: 13px;
    }

</style>
<div class="row border-bottom white-bg dashboard-header">

  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-6">
            <h4 class="">
              <span class="text-left">Total expense reports</span>
            </h4>
          </div>
          <div class="col-md-6 text-right">
            <h4>
              <span class="text-right">Start date:  <%= @start_date.strftime("%d-%b, %Y") if @start_date %> </span>
            </h4>
            <h4>
              <span class="text-right">End date:  <%= @end_date.strftime("%d-%b, %Y") if @end_date %> </span>
            </h4>
          </div>
        </div>
      </div>
      <!--<div class="alert alert-info fade in">-->
      <!--<button type="button" class="close" data-dismiss="alert">-->
      <!--<span aria-hidden="true">&times;</span>-->
      <!--</button>-->
      <!--TableTools is a plug-in for the DataTables HTML table enhancer, which adds a highly customisable button toolbar to a DataTable.-->
      <!--</div>-->
      <%= render 'total_expense_reports/reports_list_view_partial' %>
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>

app/views/total_expense_reports/date_to_date_report.xls.erb
<%= render 'total_expense_reports/reports_list_view_partial' %>

app/views/total_expense_reports/date_to_date_report_download.xls.erb
<%= render 'total_expense_reports/reports_list_view_partial' %>

app/views/total_expense_reports/date_to_date_report_search.js.erb
$('#reports_header_info').html('<%= escape_javascript render("total_expense_reports/date_to_date_search_header_info") %>');
$('#reports_holder').html('<%= escape_javascript render("total_expense_reports/reports_list_view_partial") %>');

app/views/total_expense_reports/monthly_and_yearly_report.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-md-4">
    <h2>Monthly an Yearly Reports</h2>

  </div>
  <div class="col-md-8">
    <h2 class="text-right">
        <%= select_tag 'month_id', options_from_collection_for_select(Month.all,:id, :name, :selected => @month.id), { :class =>'btn btn-white',:include_blank => 'Select month' } %>
        <%= select_tag 'year_id', options_from_collection_for_select(Year.all,:name, :name, :selected => @year.name), { :class =>'btn btn-white',:include_blank => 'Select year' } %>
        <span id="report_search" class="btn btn-default">
          <i class="fa fa-search"></i>
          Search
        </span>
    </h2>
  </div>
</div>


<!-- begin page #content -->

<!-- begin row -->
<div class="row border-bottom white-bg dashboard-header">

  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <div class="panel-heading" id="reports_header_info">
        <div class="row">
          <div class="col-md-6">
            <h4 class="">
              <span class="text-left">Total expense reports</span>
            </h4>
            <h5>
              <%= link_to monthly_and_yearly_report_total_expense_reports_path(:format => :xls), target: '_blank'  do %>
                  <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
              <% end %>
              <%= link_to monthly_and_yearly_report_total_expense_reports_path(:format => :pdf), target: '_blank'  do %>
                  <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
              <% end %>
            </h5>
          </div>
          <div class="col-md-6 text-right">
            <h4>
              <span class="text-right">Month: <%= @month ? @month.name : 'All'  %> </span>
            </h4>
            <h4>
              <span class="text-right">Year: <%= @year ? @year.name : 'All'  %> </span>
            </h4>
          </div>
        </div>
      </div>
     <div id="reports_holder">
       <%= render 'total_expense_reports/reports_list_view_partial' %>
     </div>
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>
<!-- end row -->

<!-- end page #content -->



<script>

  $('#report_search').click(function(){

      var year_id =$('#year_id').val();
      var month_id =$('#month_id').val();
      var spinner = $('<div style="text-align: center"><img src="/img/loading_spinner.gif"></div>');
      $('#reports_holder').html(spinner)
      $.ajax({
          url:'<%= monthly_and_yearly_report_search_total_expense_reports_path %>',
          type: 'get',
          data:{ year_id: year_id, month_id:month_id }
      });
  });

</script>

app/views/total_expense_reports/monthly_and_yearly_report.xls.erb
<%= render 'total_expense_reports/reports_list_view_partial' %>

app/views/total_expense_reports/monthly_and_yearly_report_download.xls.erb
<%= render 'total_expense_reports/reports_list_view_partial' %>