config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :sessions => "sessions", :registrations => "registrations" }
  root 'users#index'

    resources :users
    resources :admins do
      collection do
        get "edit_permission/:id", action: 'edit_permission', as: :edit_permission
        post "active"
      end
    end
  resources :admin_permissions
  resources :theme_customizations do
    collection do
      get 'edit_theme'
    end
  end
  resources :user_informations do
    collection do
      post 'profile_picture_change'
      post 'cropped_profile_picture_save'
    end
  end

  resources :food_categories
  resources :food_sub_categories
  resources :items do
    collection do
      get "add_to_card/:id", action: 'add_to_card', as: :add_to_card
      get "remove_from_card/:id", action: 'remove_from_card', as: :remove_from_card
      get "quantity_decrease/:id", action: 'quantity_decrease', as: :quantity_decrease
      get "order_place"
    end
  end
  resources :sub_items
  resources :customer_orders
  resources :ordered_items
  resources :product_colors
  resources :product_types
  resources :parties do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :buyers do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :bank_accounts
  resources :bank_balance_entries do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :bank_balance_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :party_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :buyer_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :expense_categories
  resources :expenses do
    collection do
      get 'search_expenses_by_category'
    end
  end

  resources :main_costs do
    collection do
      get 'expense_load_according_to_expense_category'
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :cash_balance_entries do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :cash_balance_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_product_adds do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_product_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_reports
  resources :employees do
    collection do
      post 'active'
      post 'profile_picture_change'
      post 'cropped_profile_picture_save'
    end
  end
  resources :employee_leaves do
    collection do
      get 'leave_search_according_to_employee'
      get 'leave_search_according_to_employee_download'
    end
  end

  resources :employee_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :product_imports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :product_exports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :employee_salary_adds do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :total_expense_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :total_income_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :balance_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :company_informations

end

app/models/food_category.rb
class FoodCategory < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :discount, :numericality => true
  validates_numericality_of :discount, :greater_than_or_equal_to => 0
  mount_uploader :photo, FoodCategoryPhotoUploader

  belongs_to :user
  has_many :food_sub_categories
end

app/controllers/food_categories_controller.rb
class FoodCategoriesController < ApplicationController

  def index
    @food_categories = FoodCategory.all
  end

  def show
    @food_category = FoodCategory.find(params[:id])
  end

  def create
    @food_category = FoodCategory.new(params_food_category)
    if @food_category.save
      flash[:notice] = "Food Category created successfully."
      redirect_to food_categories_path
    else
      render 'new'
    end
  end

  def edit
    @food_category = FoodCategory.find(params[:id])
  end

  def update
    @food_category = FoodCategory.find(params[:id])
    if @food_category.update(params_food_category_update)
      flash[:notice] = "Food Category updated successfully."
      redirect_to food_categories_path
    else
      render 'edit'
    end
  end

  def new
    @food_category = FoodCategory.new
  end

  protected

  def params_food_category
    params.require(:food_category).permit(:name, :isActive, :description, :discount, :photo).merge(:user_id => current_user.id)
  end

  def params_food_category_update
    params.require(:food_category).permit(:name, :isActive, :description, :discount, :photo)
  end

end

app/helpers/food_categories_helper.rb
module FoodCategoriesHelper
end

app/views/food_categories/_form.html.erb
<%= form_for @food_category do |f| %>
    <!--<form action="http://seantheme.com/" method="POST">-->
    <fieldset>
      <legend>Food Category form</legend>
      <div class="form-group">
        <% if @food_category.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@food_category.errors.count, "error") %>
              </h2>
              <ul>
                <% @food_category.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
      </div>

      <div class="form-group">
        <label for="exampleInputEmail1">Food category name*</label>
        <%= f.text_field :name, autofocus: true, :class=>"form-control", :placeholder=>"Enter food category name" %>
      </div>

      <div class="form-group">
        <label for="exampleInputEmail1">Discount</label>
        <%= f.number_field :discount, autofocus: true, :class=>"form-control", :step => 'any', :placeholder=>"Enter discount for this category" %>
      </div>



      <div class="form-group">
        <label for="exampleInputEmail1">Active or Inactive</label>
        <%= f.check_box :isActive, :class => 'i-checks' %>
      </div>

      <div class="form-group">
        <label class="">Photo of food category</label><br>
        <label title="Upload image file" for="food_category_photo" class="btn btn-primary">
          <%= f.file_field :photo , :accept =>'image/*', :class => 'hide' %>
          <i class="fa fa-upload"></i>
          <span>Upload image for this category...</span>
        </label>

      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Description for this category</label>
        <%= f.text_area :description, autofocus: true, :class=>"form-control", :placeholder=>"Enter description for this category" %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit", :class=>'btn btn-sm btn-primary m-r-5', data: { disable_with: "Submitting..." } %>
        <%= link_to 'Back', :back , data: { no_turbolink: true }, :class => 'btn btn-sm btn-default' %>
      </div>

    </fieldset>
    <!--</form>-->
<% end %>


<script>
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
    });
</script>

app/views/food_categories/edit.html.erb
<!-- begin page #content -->


<div class="row border-bottom white-bg dashboard-header">
  <!-- begin col-6 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse" data-sortable-id="form-stuff-3">
      <div class="panel-heading">
        <h3 class="">Food category edit page</h3>
      </div>
      <div class="panel-body">
        <!-- form render start -->
        <%= render 'food_categories/form' %>
        <!-- form render end -->
      </div>
    </div>
    <!-- end panel -->
  </div>
</div>
<!-- end row -->

<!-- end page #content -->


<script>
    $(document).ready(function() {
        App.init();
        FormSliderSwitcher.init();
    });
</script>

app/views/food_categories/index.html.erb
<!-- begin page #content -->

<!-- begin row -->
<div class="row border-bottom white-bg dashboard-header">

<!-- begin col-12 -->
<div class="col-md-12">
<!-- begin panel -->
<div class="panel panel-inverse">
<div class="panel-heading">

  <h3 class="">All food categories</h3>
</div>
<!--<div class="alert alert-info fade in">-->
  <!--<button type="button" class="close" data-dismiss="alert">-->
    <!--<span aria-hidden="true">&times;</span>-->
  <!--</button>-->
  <!--TableTools is a plug-in for the DataTables HTML table enhancer, which adds a highly customisable button toolbar to a DataTable.-->
<!--</div>-->
<div class="panel-body">
<div class="table-responsive">

<table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
<thead>
<tr>
  <th>Date</th>
  <th>Name</th>
  <th class="text-center">Status</th>
  <th class="">Creator</th>
  <th class="text-center">Actions</th>
</tr>
</thead>
<tbody>
<% if @food_categories.any? %>
    <% @food_categories.each do |category| %>
        <tr>
          <td>
            <%= category.created_at.strftime("%d-%m-%Y") %>
          </td>
          <td>
            <%= link_to category.name, food_category_path(category), data: { no_turbolink: true } %>
          </td>
          <td class="text-center">
            <span class="label label-<%= category.isActive ? 'success' : 'danger' %> "><%= category.isActive ? 'Active' : 'Inactive' %></span>
          </td>
          <td>
            <%= link_to category.user.email, user_information_path(category.user.user_information), data: { no_turbolink: true } %>
          </td>
          <td class="text-center">

            <%= link_to edit_food_category_path(category), data: { no_turbolink: true }, :class=>"btn btn-info btn-xs" do %>
                 Edit
                <i class="fa fa-edit"></i>
            <% end %>

          </td>
        </tr>
    <% end %>
<% end %>


</tbody>
</table>
</div>
</div>
</div>
<!-- end panel -->
</div>
<!-- end col-10 -->
</div>
<!-- end row -->

<!-- end page #content -->




<script>
    $(document).ready(function() {
        TableManageTableTools.init();
    });

</script>

app/views/food_categories/new.html.erb
<!-- begin page #content -->

<!-- begin row -->

<div class="row border-bottom white-bg dashboard-header">
  <!-- begin col-6 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse" data-sortable-id="form-stuff-3">
      <div class="panel-heading">

        <h3 class="">Food category creation page</h3>
      </div>
      <div class="panel-body">
         <!-- form render start -->
        <%= render 'food_categories/form' %>
         <!-- form render end -->
      </div>
    </div>
    <!-- end panel -->
  </div>
</div>
<!-- end row -->

<!-- end page #content -->


<script>
    $(document).ready(function() {
        FormSliderSwitcher.init();
    });
</script>

app/views/food_categories/show.html.erb
<!-- begin page #content -->

<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
  <li>
    <%= link_to 'Home', root_path, data: { no_turbolink: true }  %>
  </li>
  <li class="active">Dashboard</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Food category page <small>Details information of food category...</small></h1>
<!-- end page-header -->


<div class="profile-container">
  <!-- begin profile-section -->
  <div class="profile-section">
    <!-- begin profile-left -->
    <div class="profile-left">
      <!-- begin profile-image -->
      <div class="profile-image">
        <% if @food_category.photo? %>
            <img class="profile_image_tag" src="<%= @food_category.photo %>" fall>
        <% else %>
            <img class="profile_image_tag" src="/img/demo_profile.png" alt="" />
        <% end %>
        <i class="fa fa-user hide"></i>
      </div>
      <!-- end profile-image -->
      <div class="m-b-10">
        <!--<form id="change_profile_form">-->
          <!--<%#= hidden_field_tag :user_info_id, @user_information.id %>-->
          <!--<%#= hidden_field_tag :authenticity_token, form_authenticity_token -%>-->
          <!--<span class="btn btn-warning btn-block btn-sm fileinput-button">-->
            <!--<i class="fa fa-upload"></i>-->
            <!--<span>Upload profile photo...</span>-->
            <!--<input class="btn btn-warning btn-block btn-sm" type="file" name="user_information[profile_photo]" id="user_information_profile_photo">-->
          <!--</span>-->
        <!--</form>-->
        <!--<a href="#" class="btn btn-warning btn-block btn-sm">Change Picture</a>-->
      </div>
      <!-- begin profile-highlight -->
      <div class="profile-highlight">
        <h4><i class="fa fa-image"></i> <%= @food_category.name %> </h4>
        <!--<div class="checkbox m-b-5 m-t-0">-->
          <!--<label><input type="checkbox" /> Show my timezone</label>-->
        <!--</div>-->
        <!--<div class="checkbox m-b-0">-->
          <!--<label><input type="checkbox" /> Show i have 14 contacts</label>-->
        <!--</div>-->
      </div>
      <!-- end profile-highlight -->
    </div>
    <!-- end profile-left -->
    <!-- begin profile-right -->
    <div class="profile-right">
      <!-- begin profile-info -->
      <div class="profile-info">
        <!-- begin table -->
        <div class="table-responsive">
          <table class="table table-profile">
            <thead>
            <tr>
              <th></th>
              <th>
                <h4><%= @food_category.name %> </h4>
              </th>
              <th class="text-right">
                <h4><%= link_to 'Edit category', edit_food_category_path(@food_category), data: { no_turbolink: true }, :class=>"btn btn-default"  %></h4>
              </th>
            </tr>
            </thead>
            <tbody>
            <!--<tr class="highlight">-->
            <!--<td class="field">Mood</td>-->
            <!--<td><a href="#">Add Mood Message</a></td>-->
            <!--</tr>-->
            <!--<tr class="divider">-->
            <!--<td colspan="2"></td>-->
            <!--</tr>-->
            <tr>
              <td class="field"> Status </td>
              <td>
                <i class="fa fa-mobile fa-lg m-r-5"></i> <%= @food_category.isActive ? 'Active' : 'Inactive' %>
                <!--<a href="#" class="m-l-5">Edit</a>-->
              </td>
            </tr>
            <tr>
              <td class="field">Discount</td>
              <td>
                <%= @food_category.discount %>
              </td>
            </tr>
            <tr>
              <td class="field">Description</td>
              <td>
                <i class="fa fa-info fa-lg m-r-5"></i> <%= @food_category.description %>
                <!--<a href="#" class="m-l-5">Edit</a>-->
              </td>
            </tr>


            </tbody>
          </table>
        </div>
        <!-- end table -->
      </div>
      <!-- end profile-info -->
    </div>
    <!-- end profile-right -->
  </div>
  <!-- end profile-section -->
  <!-- begin sub categories list-->
  <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
    <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th class="text-center">Status</th>
      <th class="">Price</th>
      <th class="">Category</th>
      <th class="">Creator</th>
      <th class="text-center">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% if @food_category.food_sub_categories.any? %>
        <% @food_category.food_sub_categories.each do |sub_category| %>
            <tr>
              <td>
                <%= sub_category.created_at.strftime("%d-%m-%Y") %>
              </td>
              <td>
                <%= link_to sub_category.name, food_sub_category_path(sub_category), data: { no_turbolink: true } %>
              </td>
              <td class="text-center">
                <span class="label label-<%= sub_category.isActive ? 'success' : 'danger' %> "><%= sub_category.isActive ? 'Active' : 'Inactive' %></span>
              </td>
              <td>
                <%=  sub_category.price %>
              </td>
              <td>
                <%= link_to sub_category.food_category.name, food_category_path(sub_category.food_category), data: { no_turbolink: true } %>
              </td>
              <td>
                <%= link_to sub_category.user.email, user_information_path(sub_category.user.user_information), data: { no_turbolink: true } %>
              </td>
              <td class="text-center">

                <%= link_to edit_food_sub_category_path(sub_category), data: { no_turbolink: true }, :class=>"btn btn-info btn-xs" do %>
                    Edit
                    <i class="fa fa-edit"></i>
                <% end %>

              </td>
            </tr>
        <% end %>
    <% end %>


    </tbody>
  </table>
  <!-- end sub categories list-->

</div>

<!-- end page #content -->


<script>
    $(document).ready(function() {
        TableManageTableTools.init();
    });

</script>