config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :sessions => "sessions", :registrations => "registrations" }
  root 'users#index'

    resources :users
    resources :admins do
      collection do
        get "edit_permission/:id", action: 'edit_permission', as: :edit_permission
        post "active"
      end
    end
  resources :admin_permissions
  resources :theme_customizations do
    collection do
      get 'edit_theme'
    end
  end
  resources :user_informations do
    collection do
      post 'profile_picture_change'
      post 'cropped_profile_picture_save'
    end
  end

  resources :food_categories
  resources :food_sub_categories
  resources :items do
    collection do
      get "add_to_card/:id", action: 'add_to_card', as: :add_to_card
      get "remove_from_card/:id", action: 'remove_from_card', as: :remove_from_card
      get "quantity_decrease/:id", action: 'quantity_decrease', as: :quantity_decrease
      get "order_place"
    end
  end
  resources :sub_items
  resources :customer_orders
  resources :ordered_items
  resources :product_colors
  resources :product_types
  resources :parties do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :buyers do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :bank_accounts
  resources :bank_balance_entries do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :bank_balance_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :party_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :buyer_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :expense_categories
  resources :expenses do
    collection do
      get 'search_expenses_by_category'
    end
  end

  resources :main_costs do
    collection do
      get 'expense_load_according_to_expense_category'
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :cash_balance_entries do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :cash_balance_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_product_adds do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_product_outs do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :storage_reports
  resources :employees do
    collection do
      post 'active'
      post 'profile_picture_change'
      post 'cropped_profile_picture_save'
    end
  end
  resources :employee_leaves do
    collection do
      get 'leave_search_according_to_employee'
      get 'leave_search_according_to_employee_download'
    end
  end

  resources :employee_payments do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :product_imports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :product_exports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :employee_salary_adds do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end
  resources :total_expense_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :total_income_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :balance_reports do
    collection do
      get 'monthly_and_yearly_report'
      get 'monthly_and_yearly_report_search'
      get 'monthly_and_yearly_report_download'
      get 'date_to_date_report'
      get 'date_to_date_report_search'
      get 'date_to_date_report_download'
    end
  end

  resources :company_informations

end

app/models/employee_payment.rb
class EmployeePayment < ActiveRecord::Base
  validates :amount, :user_id, :payment_date, :employee_id, presence: true
  validates_numericality_of :amount, :greater_than_or_equal_to => 1
  validate :bank_account_validation

  belongs_to :bank_account
  belongs_to :employee
  belongs_to :user

  def bank_account_validation
    # raise bank_account_id.inspect
    if bank_account_id.nil? || bank_account_id == ''
      self.bank_account_id = 0
    end
  end
end

app/controllers/employee_payments_controller.rb
class EmployeePaymentsController < ApplicationController

  def index

  end

  def new
    @employee_payment = EmployeePayment.new
    @employee_payment.payment_date = Date.today
  end

  def create
    @employee_payment = EmployeePayment.new(params_employee_payment)
    if @employee_payment.save
      if @employee_payment.bank_account
        BankBalanceOut.create(:bank_account_id => @employee_payment.bank_account_id, :user_id => current_user.id, :to_whom => @employee_payment.employee.name, :cheque_number => @employee_payment.cheque_number, :remarks => @employee_payment.remarks, :amount => @employee_payment.amount, :flag => 3)
      else
        CashBalanceOut.create(:user_id => current_user.id, :to_whom => @employee_payment.employee.name, :remarks => @employee_payment.remarks, :amount => @employee_payment.amount, :flag => 3)
      end
      flash[:notice] = 'Employee payment added successfully.'
      redirect_to new_employee_payment_path
    else
      render 'new'
    end
  end


  def monthly_and_yearly_report
    @date = Date.today
    @month = Month.find(@date.strftime("%-m").to_i) rescue nil
    @year= Year.find_by_name(@date.strftime("%Y").to_s) rescue nil
    @reports = EmployeePayment.where(:created_at => Date.today.beginning_of_month..Date.today.end_of_month)

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def monthly_and_yearly_report_search
    @month = Month.find(params[:month_id].to_i) rescue nil
    @year= Year.find_by_name(params[:year_id].to_s) rescue nil
    @bank_account = BankAccount.find(params[:bank_account_id]) rescue nil
    @employee = Employee.find(params[:employee_id]) rescue nil

    if params[:month_id] !='' && params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i ,params[:month_id].to_i)
      @reports = EmployeePayment.where(:created_at => @year_month.beginning_of_month..@year_month.end_of_month)
    elsif params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i)
      @reports = EmployeePayment.where(:created_at => @year_month.beginning_of_year..@year_month.end_of_year)
    else
      @reports = EmployeePayment.all
    end

    if @bank_account
      @reports = @reports.where(:bank_account_id => @bank_account.id)
    end
    if @employee
      @reports = @reports.where(:employee_id => @employee.id)
    end
  end

  def monthly_and_yearly_report_download
    @month = Month.find(params[:month_id].to_i) rescue nil
    @year= Year.find_by_name(params[:year_id].to_s) rescue nil
    @bank_account = BankAccount.find(params[:bank_account_id]) rescue nil
    @employee = Employee.find(params[:employee_id]) rescue nil

    if params[:month_id] !='' && params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i ,params[:month_id].to_i)
      @reports = EmployeePayment.where(:created_at => @year_month.beginning_of_month..@year_month.end_of_month)
    elsif params[:year_id] != ''
      @year_month= DateTime.new( params[:year_id].to_i)
      @reports = EmployeePayment.where(:created_at => @year_month.beginning_of_year..@year_month.end_of_year)
    else
      @reports = EmployeePayment.all
    end

    if @bank_account
      @reports = @reports.where(:bank_account_id => @bank_account.id)
    end
    if @employee
      @reports = @reports.where(:employee_id => @employee.id)
    end

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def date_to_date_report
    @date = Date.today
    @start_date = @date.beginning_of_month
    @end_date = @date.end_of_month
    @reports = EmployeePayment.where(:created_at => Date.today.beginning_of_month..Date.today.end_of_month)

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end

  def date_to_date_report_search
    @employee = Employee.find(params[:employee_id]) rescue nil
    @bank_account = BankAccount.find(params[:bank_account_id]) rescue nil
    @start_date = Date.parse(params[:start_date])
    @end_date = Date.parse(params[:end_date])
    @reports = EmployeePayment.where(:created_at => @start_date.beginning_of_day..@end_date.end_of_day)
    if @bank_account
      @reports = @reports.where(:bank_account_id => @bank_account.id)
    end
    if @employee
      @reports = @reports.where(:employee_id => @employee.id)
    end
  end

  def date_to_date_report_download
    @employee = Employee.find(params[:employee_id]) rescue nil
    @bank_account = BankAccount.find(params[:bank_account_id]) rescue nil
    @start_date = Date.parse(params[:start_date])
    @end_date = Date.parse(params[:end_date])
    @reports = EmployeePayment.where(:created_at => @start_date.beginning_of_day..@end_date.end_of_day)
    if @bank_account
      @reports = @reports.where(:bank_account_id => @bank_account.id)
    end
    if @employee
      @reports = @reports.where(:employee_id => @employee.id)
    end

    respond_to do |format|
      format.html
      format.xls
      format.pdf do
        render pdf: "file_name"
      end
    end
  end



  protected
  def params_employee_payment
    params.require(:employee_payment).permit(:payment_date, :amount, :remarks, :cheque_number).merge(:employee_id => params[:employee_id], :bank_account_id => params[:bank_account_id], :user_id => current_user.id)
  end

end

app/helpers/employee_payments_helper.rb
module EmployeePaymentsHelper
end

app/views/employee_payments/_date_to_date_search_header_info.html.erb
<div class="row">
  <div class="col-md-6">
    <h4 class="">
      <span class="text-left">Employee payment reports</span>
    </h4>
    <h4>
      <span class="text-right">Employee: <%= @employee ? @employee.name : 'All'  %> </span>
    </h4>
    <h4>
      <span class="text-right">Bank Account: <%= @bank_account ? @bank_account.account_number : 'All'  %> </span>
    </h4>
    <h5>
      <% bank_account_id = '' %>
      <% employee_id = '' %>
      <% bank_account_id = @bank_account.id if @bank_account %>
      <% employee_id = @employee.id if @employee %>
      <%= link_to date_to_date_report_download_employee_payments_path(:format => :xls, :employee_id => employee_id, :bank_account_id => bank_account_id, :start_date=> @start_date, :end_date=> @end_date), target: '_blank'  do %>
          <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
      <% end %>
      <%= link_to date_to_date_report_download_employee_payments_path(:format => :pdf, :employee_id => employee_id, :bank_account_id => bank_account_id, :start_date=> @start_date, :end_date=> @end_date), target: '_blank'  do %>
          <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
      <% end %>
    </h5>
  </div>
  <div class="col-md-6 text-right">
    <h4>
      <span class="text-right">Start date:  <%= @start_date.strftime("%d-%b, %Y") if @start_date %> </span>
    </h4>
    <h4>
      <span class="text-right">End date:  <%= @end_date.strftime("%d-%b, %Y") if @end_date %> </span>
    </h4>
  </div>
</div>

app/views/employee_payments/_form.html.erb
<div class="row border-bottom white-bg dashboard-header">
  <!-- begin col-6 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse" data-sortable-id="form-stuff-3">

      <div class="panel-body">
        <%= form_for @employee_payment do |f| %>
            <fieldset>
              <div class="form-group">
                <% if @employee_payment.errors.any? %>
                    <div id="error_explanation">
                      <h2>
                        <%= pluralize(@employee_payment.errors.count, "Error") %>
                      </h2>
                      <ul>
                        <% @employee_payment.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>
              </div>

              <div class="form-group">
                <label for="exampleInputEmail1">Select bank account</label>
                <%= select_tag 'bank_account_id', options_from_collection_for_select(BankAccount.where(:isActive => true),:id, :account_number, :selected=>@employee_payment.bank_account_id), {:prompt=>'Select bank account', :class => 'form-control' } %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Select Employee*</label>
                <%= select_tag 'employee_id', options_from_collection_for_select(Employee.where(:isActive => true),:id, :name, :selected=>@employee_payment.employee_id), {:prompt=>'Select an employee', :class => 'form-control' } %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Amount*</label>
                <%= f.text_field :amount, autofocus: true, :class=>"form-control", :placeholder=>"Balance*" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Cheque number</label>
                <%= f.text_field :cheque_number, autofocus: true, :class=>"form-control", :placeholder=>"Cheque number" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Payment date*</label>
                <%= f.text_field :payment_date, :class=>"form-control datepicker"%>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Remarks</label>
                <%= f.text_area :remarks, autofocus: true, :class=>"form-control", :placeholder=>"Remarks" %>
              </div>


              <%= f.submit "Submit", :class=>'btn btn-sm btn-primary m-r-5', data: { disable_with: "Submiting...", confirm: "Are you sure? you want to add employee payment." } %>
              <%= link_to 'Back', :back ,data: { no_turbolink: true }, :class => 'btn btn-sm btn-default' %>
            </fieldset>
        <% end %>
      </div>
    </div>
    <!-- end panel -->
  </div>
</div>


<script>
    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
    });
</script>
<script type="text/javascript">

    $('.datepicker').datepicker({
        autoclose: true,
        todayBtn: "linked",
        format: 'yyyy/mm/dd',
        allowDeselection: false,
        forceParse: true
    });
</script>

app/views/employee_payments/_reports_header_info.html.erb
<div class="row">
  <div class="col-md-6">
    <h4 class="">
      <span class="text-left">Employee payment reports</span>
    </h4>
    <h4>
      <span class="text-right">Employee: <%= @employee ? @employee.name : 'All'  %> </span>
    </h4>
    <h4>
      <span class="text-right">Bank Account: <%= @bank_account ? @bank_account.account_number : 'All'  %> </span>
    </h4>
    <h5>
      <% bank_account_id = '' %>
      <% employee_id = '' %>
      <% year_id = '' %>
      <% month_id = '' %>
      <% month_id = @month.id if @month %>
      <% year_id = @year.name if @year %>
      <% bank_account_id = @bank_account.id if @bank_account %>
      <% employee_id = @employee.id if @employee %>
      <%= link_to monthly_and_yearly_report_download_employee_payments_path(:format => :xls, :employee_id => employee_id, :bank_account_id => bank_account_id, :year_id=> year_id, :month_id=> month_id), target: '_blank'  do %>
          <span class="label label-info"><i class="fa fa-download"></i> Download xls</span>
      <% end %>
      <%= link_to monthly_and_yearly_report_download_employee_payments_path(:format => :pdf, :employee_id => employee_id, :bank_account_id => bank_account_id, :year_id=> year_id, :month_id=> month_id), target: '_blank'  do %>
          <span class="label label-success"><i class="fa fa-download"></i> Download PDF</span>
      <% end %>
    </h5>
  </div>
  <div class="col-md-6 text-right">
    <h4>
      <span class="text-right">Month: <%= @month ? @month.name : 'All'  %> </span>
    </h4>
    <h4>
      <span class="text-right">Year: <%= @year ? @year.name : 'All'  %> </span>
    </h4>
  </div>
</div>

app/views/employee_payments/_reports_list_view_partial.html.erb
<div class="panel-body">
  <div class="table-responsive">
    <% if @reports.any? %>
        <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
          <thead>
          <tr>
            <th>Entry date</th>
            <th>Employee</th>
            <th>Account No</th>
            <th>Cheque No</th>
            <th class="text-center">payment date</th>
            <th class="text-center">Amount(tk)</th>
            <th class="text-center">remarks</th>
            <th class="text-center">Added by</th>
          </tr>
          </thead>
          <tbody>

          <% @reports.each do |report| %>
              <tr>
                <td>
                  <%= report.created_at.strftime("%d-%m-%Y") %>
                </td>
                <td>
                  <%= link_to report.employee.name, employee_path(report.employee), data: { no_turbolink: true } %>
                </td>
                <td>
                  <%= link_to report.bank_account.account_number, bank_account_path(report.bank_account), data: { no_turbolink: true } if report.bank_account %>
                </td>
                <td class="text-center">
                  <%= report.cheque_number %>
                </td>
                <td class="text-center">
                  <%= report.payment_date %>
                </td>
                <td class="text-right">
                  <%= report.amount %>
                </td>
                <td style="max-width: 150px; font-size: 8px; color: #000000" class="text-center">
                  <%= report.remarks %>
                </td>
                <td>
                  <%= link_to report.user.email, user_information_path(report.user.user_information), data: { no_turbolink: true } %>
                </td>

              </tr>
          <% end %>
          <tr>
            <td style="background:#E5E5E5" colspan="5"  class="text-center">Total amount</td>
            <td style="background:#E5E5E5;" class="text-right">
              <%= @reports.sum(:amount) %>
            </td>
            <td colspan="2"></td>
          </tr>


          </tbody>
        </table>
    <% else %>
        <h4>There is no employee payment report in this duration.</h4>
    <% end %>

  </div>
</div>

app/views/employee_payments/_reports_list_view_partial.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>


      <Row>
        <th>Date</th>
        <Cell><Data ss:Type="String">Serial No</Data></Cell>
        <Cell><Data ss:Type="String">Entry date</Data></Cell>
        <Cell><Data ss:Type="String">Employee</Data></Cell>
        <Cell><Data ss:Type="String">Account No</Data></Cell>
        <Cell><Data ss:Type="String">Cheque No</Data></Cell>
        <Cell><Data ss:Type="String">payment date</Data></Cell>
        <Cell><Data ss:Type="String">Amount(tk)</Data></Cell>
        <Cell><Data ss:Type="String">Remarks</Data></Cell>
        <Cell><Data ss:Type="String">Added by</Data></Cell>
      </Row>
      <% if @reports %>
          <% if @reports.any? %>
              <% std_count = 1 %>

              <% @reports.each do |report| %>
                  <Row>
                    <Cell><Data ss:Type="Number"><%= std_count %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.created_at.strftime('%d-%m-%Y') %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.employee.name %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.bank_account.account_number if report.bank_account %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.cheque_number %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.payment_date %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= report.amount %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.remarks %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= report.user.email  %></Data></Cell>
                  </Row>
                  <% std_count = std_count + 1 %>
              <% end %>
              <Row>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell><Data ss:Type="String">Total amount</Data></Cell>
                <Cell><Data ss:Type="Number"><%= @reports.sum(:amount) %></Data></Cell>
                <Cell></Cell>
              </Row>

              <Row></Row>
              <Row></Row>
              <Row></Row>
              <Row></Row>
              <Row></Row>

              <Row>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell></Cell>
                <Cell><Data ss:Type="String">Total amount</Data></Cell>
                <Cell><Data ss:Type="Number"><%= @reports.sum(:amount) if @reports.any? %></Data></Cell>
                <Cell></Cell>
              </Row>


    <% else %>
              <Row>
                <Cell><Data ss:Type="String">There is no employee report in this duration.</Data></Cell>
              </Row>
          <% end %>
      <% end %>

    </Table>
  </Worksheet>
</Workbook>

app/views/employee_payments/date_to_date_report.xls.erb
<%= render 'employee_payments/reports_list_view_partial' %>

app/views/employee_payments/date_to_date_report_download.pdf.erb
<style>
    table {
        font-size: 10px;
        height:auto;
        margin-top:20px;
        border-collapse: collapse;
    }
    table tr td {
        padding:5px 0 5px 5px;
        text-align: center;
        font-weight: 300;
        font-family: Arial, Helvetica, sans-serif;
        color: #353535;
        -webkit-font-smoothing: antialiased;
        font-size: 10px;
        border: .01em solid #dddddd;


    }
    table tr td a {
        text-decoration: none;
        color: #000000;
    }
    table thead tr td {
        padding:5px 0 5px 5px;
        text-align: center;
        font-weight: 400;
        font-family: Arial, Helvetica, sans-serif;
        color: #353535;
        -webkit-font-smoothing: antialiased;
        font-size: 10px;
        border: .01em solid #dadada;
    }
    h4 {
        display: block;
        margin-top: 0.5em;
        margin-bottom: 0.5em;
        margin-left: 0;
        margin-right: 0;
        font-weight: normal;
        font-size: 13px;
    }

</style>
<div class="row border-bottom white-bg dashboard-header">

  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-inverse">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-6">
            <h4 class="">
              <span class="text-left">Employee payment reports</span>
            </h4>
            <h4>
              <span class="text-right">Employee: <%= @employee ? @employee.name : 'All'  %> </span>
            </h4>
            <h4>
              <span class="text-right">Bank Account: <%= @bank_account ? @bank_account.account_number : 'All'  %> </span>
            </h4>
          </div>
          <div class="col-md-6 text-right">
            <h4>
              <span class="text-right">Start date:  <%= @start_date.strftime("%d-%b, %Y") if @start_date %> </span>
            </h4>
            <h4>
              <span class="text-right">End date:  <%= @end_date.strftime("%d-%b, %Y") if @end_date %> </span>
            </h4>
          </div>
        </div>
      </div>
      <!--<div class="alert alert-info fade in">-->
      <!--<button type="button" class="close" data-dismiss="alert">-->
      <!--<span aria-hidden="true">&times;</span>-->
      <!--</button>-->
      <!--TableTools is a plug-in for the DataTables HTML table enhancer, which adds a highly customisable button toolbar to a DataTable.-->
      <!--</div>-->
      <%= render 'employee_payments/reports_list_view_partial' %>
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-10 -->
</div>

app/views/employee_payments/date_to_date_report_search.js.erb
$('#reports_header_info').html('<%= escape_javascript render("employee_payments/date_to_date_search_header_info") %>');
$('#reports_holder').html('<%= escape_javascript render("employee_payments/reports_list_view_partial") %>');

app/views/employee_payments/monthly_and_yearly_report.xls.erb
<%= render 'employee_payments/reports_list_view_partial' %>

app/views/employee_payments/monthly_and_yearly_report_download.xls.erb
<%= render 'employee_payments/reports_list_view_partial' %>

app/views/employee_payments/monthly_and_yearly_report_search.js.erb
$('#reports_header_info').html('<%= escape_javascript render("employee_payments/reports_header_info") %>');
$('#reports_holder').html('<%= escape_javascript render("employee_payments/reports_list_view_partial") %>');

app/views/employee_payments/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Employee Payment Add</h2>

  </div>
  <div class="col-lg-2">

  </div>
</div>
<%= render 'form' %>